//
//  Poem.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers
class Poem: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _id: String?
    var _title: String?
    var _fileName: String?
    var _updatedAt: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "alztest-mobilehub-1310991232-poem"
    }
    
    class func hashKeyAttribute() -> String {

        return "_id"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_title"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_id" : "id",
               "_title" : "title",
               "_fileName" : "fileName",
               "_updatedAt" : "updatedAt",
        ]
    }
}
