//
//  Recording.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers
class Recording: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _id: String?
    var _poemId: String?
    var _poemTitle: String?
    var _updatedAt: NSNumber?
    var _fileName: String?
    var _htmlFileName: String?
    
    
    
    class func dynamoDBTableName() -> String {

        return "alztest-mobilehub-1310991232-recording"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_poemTitle"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_id" : "id",
               "_poemId" : "poemId",
               "_poemTitle" : "poemTitle",
               "_updatedAt" : "updatedAt",
               "_fileName" : "fileName",
               "_htmlFileName" : "htmlFileName",
        ]
    }
}
